defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      animation: false
      layout: default
      title: MIT URTC 2019
sass:
  sass_dir: _scss
  style: compressed
url: "https://urtc.mit.edu"
